name: Build and Test Aster Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        # Install OpenGL development files, GLEW, GLFW, and Catch2 for testing
        sudo apt-get install -y libgl1-mesa-dev libglew-dev libglfw3-dev catch2
        
    - name: Setup dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        # Install GLEW and GLFW (OpenGL is included in macOS)
        brew install glew glfw catch2
        # Set up environment variables for CMake to find the libraries
        echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/glew:/opt/homebrew/opt/glfw:/opt/homebrew/opt/catch2" >> $GITHUB_ENV

    - name: Setup dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Install required libraries using vcpkg
        vcpkg install opengl:x64-windows glew:x64-windows glfw3:x64-windows catch2:x64-windows
        echo "CMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV

    - name: Configure CMake (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_PREFIX_PATH=${{ env.CMAKE_PREFIX_PATH }}

    - name: Configure CMake (non-macOS)
      if: matrix.os != 'macos-latest'
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.os == 'windows-latest' && '-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake' || '' }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      shell: bash
      run: |
        ctest -C ${{ matrix.build_type }} --output-on-failure

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}-${{ matrix.build_type }}
        path: build
