name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libglew-dev xorg-dev libgl1-mesa-dev
        
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install glfw
        brew install glew
        
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        vcpkg install glfw3:x64-windows
        vcpkg install glew:x64-windows
        vcpkg integrate install
        
    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake
        
    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure
